'''
Created on Jan 3, 2017

@author: devdatta
'''
from os.path import expanduser

DEFAULT_DB_USER = 'testuser'
DEFAULT_DB_PASSWORD = 'testpass123!#$'
DEFAULT_DB_NAME = 'testdb'

home_dir = expanduser("~")

APP_STORE_PATH = ("{home_dir}/.cld/data/deployments").format(home_dir=home_dir)

GOOGLE_CREDS_PATH = APP_STORE_PATH + "/google-creds"

DEPLOYING_APP = "DEPLOYING_APP"
APP_DEPLOYMENT_COMPLETE = "APP_DEPLOYMENT_COMPLETE"

DEPLOYING_SERVICE_INSTANCE = "DEPLOYING_SERVICE_INSTANCE"
SERVICE_INSTANCE_DEPLOYMENT_COMPLETE = "SERVICE_DEPLOYMENT_COMPLETE"

DB_USER = "USER"
DB_USER_PASSWORD = "PASSWORD"
DB_ROOT_PASSWORD = "ROOT_PASSWORD"
DB_HOST = "HOST"
DB_NAME = "DB_NAME"

RDS_INSTANCE = "RDS_INSTANCE"

CLOUD_SQL_CONNECTION_STR = "CONNECTION_STR"
MYSQL_VERSION = "MYSQL_VERSION"
CLOUD_SQL_TIER = "CLOUD_SQL_TIER"
CLOUD_SQL_INSTANCE = "CLOUD_SQL_INSTANCE"

SQL_CONTAINER = "SQL_CONTAINER"

LOCAL_DOCKER = "local-docker"
GOOGLE = "google"
AWS = "aws"
